### PR TITLE
Add options to install python/ruby in system standard paths

### PR DESCRIPTION
**Pull request by j-rivero**
# 🎉 New feature

## Summary

Introduce two new options: `USE_SYSTEM_PATHS_FOR_PYTHON_INSTALLATION` and `USE_DIST_PACKAGES_FOR_PYTHON` to support python installation in the standard directories. The local installations can go in `<path>/site-packages` (i.e /usr/lib/python3/site-packages) but for packaging Debian is recommending to use `<path>/dist-packages`.

The best way to implement this is to use the `find_package(Python3)` but is only available from 3.12 on so I've implemented a workaround invoking 

## Checklist
- [x] Signed all commits for DCO

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by chapulina** [comment]
This is being tested in https://github.com/ignition-release/ign-math6-release/pull/6

**Review by chapulina — APPROVED** [review]
LGTM

I noticed that SWIG is not being found on macOS and Windows CI even without this PR. So note that these paths haven't really been tested on those platforms. Not this PR's fault though.

**Comment by scpeters** [comment]
> LGTM
> 
> I noticed that SWIG is not being found on macOS and Windows CI even without this PR. So note that these paths haven't really been tested on those platforms. Not this PR's fault though.

we can enable SWIG by adding it as a dependency to the [ignition-math6](https://github.com/osrf/homebrew-simulation/blob/master/Formula/ignition-math6.rb) formula. I just tested it locally and there are some extra compiler warnings and test failures related to random number generation in Ruby.

**Comment by chapulina** [comment]
> we can enable SWIG 

Ticketed https://github.com/ignition-tooling/release-tools/issues/508

**Pull request merged**
