### PR TITLE
Add codecheck to focal CI

### PR DESCRIPTION
**Pull request by mjcarroll**
This is a workaround to enable codecheck on ign-math before we turn it on globally for focal.

Since `ign-math7`/`main` is only supported on `focal` forward, it makes sense to turn these checks on.

Signed-off-by: Michael Carroll <michael@openrobotics.org>

### CODE REVIEW

**Comment by chapulina** [comment]
How about enabling this through the action? If it's centralized, we can flip the switch to make checking the default for all libraries more easily. It also prevents adding a new `between_cmake_make.sh` file to all libraries.

**Comment by mjcarroll** [comment]
I think that makes sense, I had that thought after I opened this PR, moving this back to draft for now.

**Comment by mjcarroll** [comment]
This is now using the branch from ignition-tooling/action-ignition-ci#43.  Once that lands, this will revert back to the `focal` branch of that repo.

**Comment by mjcarroll** [comment]
Tooling branch is merged, this is ready for review

**Comment by mjcarroll** [comment]
Confirmed it worked: 
image

**Review by chapulina — APPROVED** [review]

**Pull request merged**
