### PR TITLE
Master branch updates

### PR DESCRIPTION
**Pull request by chapulina**
Part of  https://github.com/ignition-tooling/release-tools/issues/416

## Summary

Update all usage of `master`

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by scpeters** [comment]
@osrf-jenkins run tests please

**Review by adlarkin — APPROVED** [review]
I did a quick repository search (thanks `git grep`), and noticed that the link [here](https://github.com/ignitionrobotics/ign-math/blob/chapulina/bye_master/include/ignition/math/MassMatrix3.hh#L561) no longer works. I believe it should be:
```
https://github.com/RobotLocomotion/drake/blob/master/multibody/tree/rotational_inertia.h
```

Should we make that change here before merging?

**Comment by chapulina** [comment]
> Should we make that change here before merging?

Oops, auto-merge didn't give us a chance. Feel free to open a new PR with that change. Unfortunately, links tend to deteriorate over time :confused:

**Comment by adlarkin** [comment]
> Oops, auto-merge didn't give us a chance. Feel free to open a new PR with that change. Unfortunately, links tend to deteriorate over time

No worries, I forgot that we picked auto-merge here. Here's a PR with the change: https://github.com/ignitionrobotics/ign-math/pull/197

**Pull request merged**
