### PR TITLE
Internal URL fixed (paragraph 266)

### PR DESCRIPTION
**Pull request by kant**
# 🦟 Bug fix

No Fixes any previous PR

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

Signed-off-by: Darío Hereñú <magallania@gmail.com>

### CODE REVIEW

**Review by scpeters — APPROVED** [review]

**Review by chapulina — APPROVED** [review]
Nice catch, thanks! Can you [sign your commit for the DCO checker](https://ignitionrobotics.org/docs/all/contributing#process)?

**Comment by ahcorde** [comment]
friendly ping @kant

**Comment by ahcorde** [comment]
@kant the DCO is still failing. You can try this:

```bash
git reset --hard HEAD~2
git commit --amend --no-edit --signoff
git push -f origin patch-1
```

**Comment by kant** [comment]
> @kant the DCO is still failing. You can try this:
> 
> ```shell
> git reset --hard HEAD~2
> git commit --amend --no-edit --signoff
> git push -f origin patch-1
> ```

After the last script `git push -f origin patch-1` 
the prompt alerts me this: 
```
error: src refspec patch-1 does not match any
error: failed to push some refs to 'https://github.com/kant/ign-math.git'
```

**Comment by ahcorde** [comment]
@kant , 

did you fetch your repo and checkout the right branch?

```bash
git clone https://github.com/kant/ign-math
cd ign-math
git checkout patch-1
git reset --hard HEAD~2
git commit --amend --no-edit --signoff
git push -f origin patch-1
```

**Comment by ahcorde** [comment]
@kant, did you try the last suggestion?

**Comment by kant** [comment]
Done! (following this procedures:
```git clone https://github.com/kant/ign-math
cd ign-math
git checkout patch-1
git reset --hard HEAD~2
git commit --amend --no-edit --signoff
git push -f origin patch-1
```

**Comment by chapulina** [comment]
Thanks again, @kant !

**Comment by kant** [comment]
Thanks for sharing your knowledge. It is a pleasure to contribute to this project. Kudos and thanks for your patience @ahcorde @chapulina @scpeters @clalancette !!

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-03-01-citadel-edifice-fortress/1313/1

**Pull request merged**
