### PR TITLE
Remove tools in favor of `make codecheck`

### PR DESCRIPTION
**Pull request by chapulina**
## Summary

Removing:

* `tools/code_check.sh` and family, which used to be used on Jenkins but hasn't been working, see https://github.com/ignition-tooling/release-tools/issues/446

In favor of:

* `make codecheck`, which is used on Actions and can't be used (nicely) on Jenkins yet because of https://github.com/ignition-tooling/release-tools/issues/148

## Test it

Check out CI results

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

### CODE REVIEW

**Comment by scpeters** [comment]
we still need `tools/check_test_ran.py`

**Comment by chapulina** [comment]
> we still need tools/check_test_ran.py

Restored in 1c4e12d. Do you think this is something reasonable to move to `ign-cmake`?

**Comment by chapulina** [comment]
> something reasonable to move to ign-cmake?

Probably yes, it's used by it: https://github.com/ignitionrobotics/ign-cmake/blob/17b7058ff5c9de2f6f396d1a000dd0366481d621/cmake/IgnUtils.cmake#L1721

**Comment by scpeters** [comment]
> > something reasonable to move to ign-cmake?
> 
> Probably yes, it's used by it: https://github.com/ignitionrobotics/ign-cmake/blob/17b7058ff5c9de2f6f396d1a000dd0366481d621/cmake/IgnUtils.cmake#L1721

since we aren't using QTest anymore (https://github.com/ignitionrobotics/ign-gui/issues/198#issuecomment-809640183), I think it can be moved to ign-cmake. There are a few variants of `check_test_ran.py` in our packages, so we should make sure to get the one that uses an informative `classname`:

* not helpful: https://github.com/ignitionrobotics/ign-cmake/blob/ign-cmake2/tools/check_test_ran.py#L73
* helpful: https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo5/tools/check_test_ran.py#L73

**Comment by chapulina** [comment]
It looks like we don't even need https://github.com/ignition-tooling/release-tools/pull/455, the job already ignores a missing `code_check` file:

```
sh: 0: Can't open tools/code_check.sh
+ true
```

**Review by scpeters — APPROVED** [review]

**Comment by chapulina** [comment]
> I think it can be moved to ign-cmake

* Removed `check_test_ran` from this repo in e12d976.
* Updating `ign-cmake` in https://github.com/ignitionrobotics/ign-cmake/pull/168
* Test run: [Build Status](https://build.osrfoundation.org/job/ignition_math-ci-pr_any-ubuntu_auto-amd64/552/) (uses https://github.com/ignition-tooling/release-tools/compare/chapulina/math/211)

**Pull request merged**
